apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gcp-devops
  name: gcp-devops
  namespace: gcp-devops-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-devops
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gcp-devops
    spec:
      containers:
      - image: gcr.io//gcpdevops
        name: gcpdevops
        ports:
        - containerPort: 5000
        env:
          - name: PORT 
            value: "5000"