apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gcp-devops
  name: gcp-devops
  namespace: gcp-devops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-devops
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gcp-devops
    spec:
      containers:
      - image: gcr.io/level-epoch-436108-t8/gcpdevops-dev:latest
        name: gcpdevops
        ports:
        - containerPort: 5000
        env:
          - name: PORT 
            value: "5000"
------

apiVersion: "v1"
kind: "Service"
metadata:
  name: "gcp-devops-gke-service"
  namespace: "gcp-devops-dev"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"

spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  selector:
    app: gcp-devops
  type: "LoadBalancer"